local GetSpellCharges = C_Spell.GetSpellCharges
local GetNumSpellBookSkillLines = C_SpellBook.GetNumSpellBookSkillLines
local GetSpellBookSkillLineInfo = C_SpellBook.GetSpellBookSkillLineInfo
local GetSpellBookItemInfo = C_SpellBook.GetSpellBookItemInfo
local IsSpellPassive = C_Spell.IsSpellPassive
local IsSpellBookItemOffSpec = C_SpellBook.IsSpellBookItemOffSpec
local InsertTable = table.insert
local Wipe = wipe
local GetUnitAuraInstanceIDs = C_UnitAuras.GetUnitAuraInstanceIDs
local GetAuraDataByAuraInstanceID = C_UnitAuras.GetAuraDataByAuraInstanceID
local GetAuraDuration = C_UnitAuras.GetAuraDuration
local GetAuraApplicationDisplayCount = C_UnitAuras.GetAuraApplicationDisplayCount
local GetAuraDispelTypeColor = C_UnitAuras.GetAuraDispelTypeColor
local DoesAuraHaveExpirationTime = C_UnitAuras.DoesAuraHaveExpirationTime
local UnitHealthPercent = UnitHealthPercent
local UnitPowerPercent = UnitPowerPercent
local UnitGetTotalHealAbsorbs = UnitGetTotalHealAbsorbs
local UnitGetTotalAbsorbs = UnitGetTotalAbsorbs
local UnitHealthMax = UnitHealthMax
local UnitClass = UnitClass
local UnitGroupRolesAssigned = UnitGroupRolesAssigned
local UnitIsUnit = UnitIsUnit
local UnitIsEnemy = UnitIsEnemy
local UnitIsDeadOrGhost = UnitIsDeadOrGhost
local UnitExists = UnitExists
local UnitCanAttack = UnitCanAttack
local UnitChannelDuration = UnitChannelDuration
local UnitCastingDuration = UnitCastingDuration
local UnitInVehicle = UnitInVehicle
local EvaluateColorFromBoolean = C_CurveUtil.EvaluateColorFromBoolean
local IsMounted = IsMounted
local GetUnitSpeed = GetUnitSpeed
local UnitAffectingCombat = UnitAffectingCombat
local UnitCastingInfo = UnitCastingInfo
local UnitChannelInfo = UnitChannelInfo
local IsSpellUsable = C_Spell.IsSpellUsable
local GetSpellTexture = C_Spell.GetSpellTexture
local GetSpellChargeDuration = C_Spell.GetSpellChargeDuration
local GetSpellCooldownDuration = C_Spell.GetSpellCooldownDuration
local GetSpellLink = C_Spell.GetSpellLink
local CreateColorCurve = C_CurveUtil.CreateColorCurve


-- [unit]存在 → unitExists
-- [unit]存活 → unitIsAlive
-- [unit]的职业 → unitClass
-- [unit]的职责 → unitRole
-- [unit]的血量 → unitHealthPercent
-- [unit]的能量 → unitPowerPercent
-- [unit]是敌人 → unitIsEnemy
-- [unit]可以攻击 → unitCanAttack
-- [unit]施法图标 → unitCastIcon
-- [unit]通道法术图标 → unitChannelIcon
-- [unit]施法进度 → unitCastProgress
-- [unit]通道法术进度 → unitChannelProgress
-- [unit]施法可打断 → unitCastIsInterruptible
-- [unit]通道法术可打断 → unitChannelIsInterruptible
-- [unit]在远程范围 → unitIsInRangedRange
-- [unit]在近战范围 → unitIsInMeleeRange
-- [unit]在战斗中 → unitIsInCombat
-- [unit]是当前目标 → unitIsTarget
